config/routes.rb
many_id_re = /([a-z0-9\-]+\,[a-z0-9\-]+\,{0,1})+/

Rails.application.routes.draw do
  controller :letsencrypt do
    get '/.well-known/acme-challenge/gNCtCbL-vk4TWp3wZAUBz5MF5kxwHEQaFOwUmM1JLb4' => :show
  end

  namespace :api, path: '/', format: :json do
    namespace :v2, path: '(v2)', constraints: APIConstraint.new(2) do
      namespace :manager do
        controller :accounts do
          get    '/account'  => :show,   as: :account
          put    '/account'  => :update
          delete '/account'  => :destroy
          post   '/accounts' => :create, as: :accounts
        end

        controller :verifications do
          put '/verifications/:token' => :update
        end

        controller :passwords do
          post '/passwords'        => :create
          put  '/passwords/:token' => :update
        end

        controller :sessions do
          get    '/session'  => :show,    as: :session
          delete '/session'  => :destroy
          put    '/session'  => :update
          post   '/sessions' => :create,  as: :sessions
        end

        controller :keys do
          get    '/keys'     => :index,  as: :keys
          post   '/keys'     => :create
          get    '/keys/:id' => :show,   as: :key
          put    '/keys/:id' => :update
          delete '/keys/:id' => :destroy
        end
      end

      match '*path', to: 'api#preflight_cors', via: :options

      controller :datasets do
        get '/datasets'     => :index, as: :datasets
        get '/datasets/:id' => :index, constraints: { id: many_id_re }
        get '/datasets/:id' => :show,  as: :dataset
      end

      controller :inventories do
        get '/inventories'     => :index, as: :inventories
        get '/inventories/:id' => :index, constraints: { id: many_id_re }
        get '/inventories/:id' => :show, as: :inventory
        get '/products/:product_id/stores/:store_id' => redirect('/inventories/%{product_id}-%{store_id}')
        get '/stores/:store_id/products/:product_id' => redirect('/inventories/%{product_id}-%{store_id}')
      end

      controller :products do
        get '/products'     => :index, as: :products
        get '/products/:id' => :index, constraints: { id: many_id_re }
        get '/products/:id' => :show,  as: :product
      end

      controller :stores do
        get '/stores'     => :index, as: :stores
        get '/stores/:id' => :index, constraints: { id: many_id_re }
        get '/stores/:id' => :show,  as: :store
      end

      controller :producers do
        get '/producers'     => :index, as: :producers
        get '/producers/:id' => :index, constraints: { id: many_id_re }
        get '/producers/:id' => :show,  as: :producer
      end

      controller :categories do
        get '/categories'     => :index, as: :categories
        get '/categories/:id' => :index, constraints: { id: many_id_re }
        get '/categories/:id' => :show,  as: :category
      end
    end

    scope module: :v1, path: '(v1)', constraints: APIConstraint.new(1, true) do
      match '*path', to: 'api#preflight_cors', via: :options

      # Legacy V1
      get '/products/search'                          => 'products#index'
      get '/products/:product_id/inventory'           => 'inventories#index'
      get '/stores/search'                            => 'stores#index'
      get '/stores/near/geo(/with/:product_id)'       => 'stores#index',    is_geo_q: true
      get '/stores/near/:geo(/with/:product_id)'      => 'stores#index'
      get '/stores/near/:lat/:lon(/with/:product_id)' => 'stores#index', constraints: { lat: GeoScope::LATLON_RE, lon: GeoScope::LATLON_RE }
      get '/stores/:store_id/products/search'         => 'products#index'

      resources :datasets, only: [:index, :show]

      resources :products, only: [:index, :show] do
        resources :inventories, only: [:index], controller: 'inventories'
        resources :stores,      only: [:index]
      end

      resources :stores, only: [:index, :show] do
        resources :products, only: [:index] do
          get 'inventory' => 'inventories#show', as: :store_inventory
        end
      end

      resources :inventories, only: [:index]
    end
  end

  scope controller: :root, action: :ember, format: :html do
    get '/sign-up'      => redirect('/manager/sign-up')
    get '/log-in'       => redirect('/manager/log-in')
    get '/manage'       => redirect('/manager')
    get '/manage/*path' => redirect('/manager/%{path}')
    get '/manager'
    get '/manager/log-in'
    get '/manager/sign-up'
    get '/manager/verify/:token',   as: :verify_token
    get '/manager/password/recover'
    get '/manager/password/:token', as: :password
    get '/manager/account'
    get '/manager/keys'
    get '/manager/keys/new'
    get '/manager/keys/:key_id'
    get '/manager/credits'
    get '/manager/terms'
    get '/manager/privacy'
  end

  namespace :admin do
    root to: 'crawls#index'

    resources :crawls
    resources :crawl_events
    resources :users

    resources :plans do
      member do
        put :clone
      end
    end
  end
end

app/models/crawl.rb
class Crawl < ApplicationRecord
  include RedisAbuse::Model

  class StateError < StandardError; end

  SERIALIZED_FIELDS = [
    :store_ids,
    :product_ids,
    :added_product_ids,
    :added_store_ids,
    :removed_product_ids,
    :removed_store_ids]

  STATES = %w[
    init
    running
    paused
    cancelled
    finished
  ]

  list :crawled_store_ids,   :integer
  list :crawled_product_ids, :integer

  after_save :check_if_cancelled

  validates :state, inclusion: { in: STATES }

  SERIALIZED_FIELDS.each do |f|
    serialize(f)
  end

  scope :is, ->(*states) { where(state: states.map(&:to_s)) }

  belongs_to :crawl_event, optional: true
  has_many :crawl_events

  def self.latest
    order(id: :desc).first
  end

  def self.any_active?
    is(:init, :running, :paused).count != 0
  end

  def self.init
    raise 'Crawl is already running' if any_active?
    create(
      state: 'init',
      store_ids: [],
      product_ids: [],
      added_product_ids: [],
      added_store_ids: [],
      removed_product_ids: [],
      removed_store_ids: []
    )
  end

  def previous
    @previous ||= begin
      Crawl.
        where("id != ? AND state = 'finished'", id).
        order(id: :desc).
        first
    end
  end

  def state=(val)
    write_attribute :state, val ? val.to_s : val
  end

  def diff!
    self.store_ids   = crawled_store_ids.all
    self.product_ids = crawled_product_ids.all

    if previous
      self.added_product_ids   = (product_ids - previous.product_ids)
      self.removed_product_ids = (previous.product_ids - product_ids)
      self.added_store_ids     = (store_ids - previous.store_ids)
      self.removed_store_ids   = (previous.store_ids - store_ids)
    else
      self.added_product_ids   = []
      self.removed_product_ids = []
      self.added_store_ids     = []
      self.removed_store_ids   = []
    end

    save!
  end

  def is?(*states)
    states.map(&:to_s).include?(self.state)
  end

  def is_locked?
    is? :finished, :cancelled
  end

  def is_active?
    is? :init, :running, :paused
  end

  def log(message, level = :info, payload = {})
    verify_unlocked!

    ce = CrawlEvent.create!(
      crawl_id:   id,
      level:      level.to_s,
      message:    message.to_s,
      payload:    JSON.dump(payload))

    self.crawl_event_id = ce.id

    save!
  end

  protected

  def check_if_cancelled
    return true unless state == 'cancelled'
    AdminMailer.crawl_cancelled_message(self.id).deliver
  end

  def verify_unlocked!
    raise StateError, "Crawl is #{state}" if is_locked?
  end
end

app/controllers/admin/crawls_controller.rb
class Admin::CrawlsController < AdminController
  def index
    @crawls = Crawl.order(id: :desc).limit(20).all
  end

  def show
    @crawl  = Crawl.find(params[:id])
    @events = @crawl.crawl_events.order(id: :desc).limit(50).all
  end
end

app/views/admin/crawls/index.html.erb
<section>
  <div class="page-header">
    <h1>Crawls</h1>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Started</th>
        <th scope="col">Elapsed Time</th>
        <th scope="col">Status</th>
        <th scope="col">Log</th>
      </tr>
    </thead>
    <tbody>
      <% @crawls.each do |crawl| %>
        <%-
          crawl_class = {
            'finished' => 'finished',
            'paused'   => 'info',
            'failed'   => 'danger',
            'running'  => 'success'
          }[crawl.state]
        -%>
        <tr class="<%= crawl_class %>">
          <td>
            <%= link_to admin_crawl_path(crawl) do %>
              <%= nice :datetime, crawl.created_at %>
            <% end %>
          </td>
          <td>
            <%= distance_of_time_in_words(crawl.created_at, crawl.updated_at, include_seconds: true) %>
          </td>
          <td>
            <%= crawl.state %>
          </td>
          <% crawl.crawl_event.tap do |ev| %>
            <td class="<%= ev ? ev.level : nil %>">
              <%= ev.try(:message) %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<section>

app/views/admin/crawls/show.html.erb
<h1>Crawl</h1>

<dl class="crawl-info">
  <dt>Start Time</dt>
  <dd><%= nice :datetimesec, @crawl.created_at %></dd>
  <dt>Elapsed Time</dt>
  <dd><%= distance_of_time_in_words @crawl.created_at, @crawl.updated_at, include_seconds: true %></dd>
  <dt>Status</dt>
  <dd><%= @crawl.state %></dd>
  <dt>Total Stores<dt>
  <dd>
    <%= @crawl.total_stores %>
  </dd>
  <dt>Total Products</dt>
  <dd>
    <%= @crawl.total_products %>
  </dd>
  <dt>Total Inventories</dt>
  <dd>
    <%= @crawl.total_inventories %>
  </dd>
</dl>

<table class="crawl-events">
  <tr>
    <th>Time</th>
    <th>Message</th>
  </tr>
  <% @events.each do |ev| %>
    <tr class="<%= ev.level %>">
      <td>
        <%= link_to admin_crawl_event_path(ev) do %>
          <%= nice :datetimesec, ev.created_at %>
        <% end %>
      </td>
      <td>
        <%= ev.message %>
      </td>
    </tr>
  <% end %>
</table>