config/routes.rb
many_id_re = /([a-z0-9\-]+\,[a-z0-9\-]+\,{0,1})+/

Rails.application.routes.draw do
  controller :letsencrypt do
    get '/.well-known/acme-challenge/gNCtCbL-vk4TWp3wZAUBz5MF5kxwHEQaFOwUmM1JLb4' => :show
  end

  namespace :api, path: '/', format: :json do
    namespace :v2, path: '(v2)', constraints: APIConstraint.new(2) do
      namespace :manager do
        controller :accounts do
          get    '/account'  => :show,   as: :account
          put    '/account'  => :update
          delete '/account'  => :destroy
          post   '/accounts' => :create, as: :accounts
        end

        controller :verifications do
          put '/verifications/:token' => :update
        end

        controller :passwords do
          post '/passwords'        => :create
          put  '/passwords/:token' => :update
        end

        controller :sessions do
          get    '/session'  => :show,    as: :session
          delete '/session'  => :destroy
          put    '/session'  => :update
          post   '/sessions' => :create,  as: :sessions
        end

        controller :keys do
          get    '/keys'     => :index,  as: :keys
          post   '/keys'     => :create
          get    '/keys/:id' => :show,   as: :key
          put    '/keys/:id' => :update
          delete '/keys/:id' => :destroy
        end
      end

      match '*path', to: 'api#preflight_cors', via: :options

      controller :datasets do
        get '/datasets'     => :index, as: :datasets
        get '/datasets/:id' => :index, constraints: { id: many_id_re }
        get '/datasets/:id' => :show,  as: :dataset
      end

      controller :inventories do
        get '/inventories'     => :index, as: :inventories
        get '/inventories/:id' => :index, constraints: { id: many_id_re }
        get '/inventories/:id' => :show, as: :inventory
        get '/products/:product_id/stores/:store_id' => redirect('/inventories/%{product_id}-%{store_id}')
        get '/stores/:store_id/products/:product_id' => redirect('/inventories/%{product_id}-%{store_id}')
      end

      controller :products do
        get '/products'     => :index, as: :products
        get '/products/:id' => :index, constraints: { id: many_id_re }
        get '/products/:id' => :show,  as: :product
      end

      controller :stores do
        get '/stores'     => :index, as: :stores
        get '/stores/:id' => :index, constraints: { id: many_id_re }
        get '/stores/:id' => :show,  as: :store
      end

      controller :producers do
        get '/producers'     => :index, as: :producers
        get '/producers/:id' => :index, constraints: { id: many_id_re }
        get '/producers/:id' => :show,  as: :producer
      end

      controller :categories do
        get '/categories'     => :index, as: :categories
        get '/categories/:id' => :index, constraints: { id: many_id_re }
        get '/categories/:id' => :show,  as: :category
      end
    end

    scope module: :v1, path: '(v1)', constraints: APIConstraint.new(1, true) do
      match '*path', to: 'api#preflight_cors', via: :options

      # Legacy V1
      get '/products/search'                          => 'products#index'
      get '/products/:product_id/inventory'           => 'inventories#index'
      get '/stores/search'                            => 'stores#index'
      get '/stores/near/geo(/with/:product_id)'       => 'stores#index',    is_geo_q: true
      get '/stores/near/:geo(/with/:product_id)'      => 'stores#index'
      get '/stores/near/:lat/:lon(/with/:product_id)' => 'stores#index', constraints: { lat: GeoScope::LATLON_RE, lon: GeoScope::LATLON_RE }
      get '/stores/:store_id/products/search'         => 'products#index'

      resources :datasets, only: [:index, :show]

      resources :products, only: [:index, :show] do
        resources :inventories, only: [:index], controller: 'inventories'
        resources :stores,      only: [:index]
      end

      resources :stores, only: [:index, :show] do
        resources :products, only: [:index] do
          get 'inventory' => 'inventories#show', as: :store_inventory
        end
      end

      resources :inventories, only: [:index]
    end
  end

  scope controller: :root, action: :ember, format: :html do
    get '/sign-up'      => redirect('/manager/sign-up')
    get '/log-in'       => redirect('/manager/log-in')
    get '/manage'       => redirect('/manager')
    get '/manage/*path' => redirect('/manager/%{path}')
    get '/manager'
    get '/manager/log-in'
    get '/manager/sign-up'
    get '/manager/verify/:token',   as: :verify_token
    get '/manager/password/recover'
    get '/manager/password/:token', as: :password
    get '/manager/account'
    get '/manager/keys'
    get '/manager/keys/new'
    get '/manager/keys/:key_id'
    get '/manager/credits'
    get '/manager/terms'
    get '/manager/privacy'
  end

  namespace :admin do
    root to: 'crawls#index'

    resources :crawls
    resources :crawl_events
    resources :users

    resources :plans do
      member do
        put :clone
      end
    end
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  enum kind: [
    :free,
    :supporter,
    :developer,
    :enterprise
  ]

  has_many :users

  after_save :recache_users

  scope :with_users_count, -> {
    select('plans.*, count(users.id) AS users_count').
    joins('LEFT OUTER JOIN users ON users.plan_id = plans.id').
    group('plans.id')
  }

  def self.select_options
    with_users_count.order(updated_at: :desc).map { |plan|
      ["#{plan.title} (#{plan.kind.titlecase}, #{plan.users_count} users)", plan.id]
    }
  end

  def clone(params = {})
    Plan.create!({
      kind:              kind,
      is_active:         is_active,
      title:             title,
      has_cors:          has_cors,
      has_ssl:           has_ssl,
      has_upc_lookup:    has_upc_lookup,
      has_upc_value:     has_upc_value,
      has_history:       has_history,
      request_pool_size: request_pool_size,
      fee_in_cents:      fee_in_cents
    }.merge(params))
  end

  private

  def recache_users
    users.find_each(&:redis_cache)
    true
  end
end

app/controllers/admin/plans_controller.rb
class Admin::PlansController < ApplicationController
  def index
    @plans = Plan.with_users_count.order(kind: :asc, created_at: :desc)
  end

  def show
    @plan = Plan.with_users_count.find(params[:id])
  end

  def destroy
    @plan = Plan.with_users_count.find(params[:id])

    if @plan.users_count == 0
      @plan.destroy
      redirect_to admin_plans_url
    else
      redirect_to admin_plan_url(@plan)
    end
  end

  def new
    @plan = Plan.new
    render :show
  end

  def create
    @plan = Plan.create(plan_params)

    if @plan.valid?
      redirect_to admin_plan_url(@plan)
    else
      render :show
    end
  end

  def update
    @plan = Plan.find(params[:id])

    if @plan.update(plan_params)
      redirect_to admin_plan_url(@plan)
    else
      render :show
    end
  end

  def clone
    plan = Plan.find(params[:id])
    clone = @plan.clone
    redirect_to admin_plan_url(clone)
  end

  private

  def plan_params
    params.require(:plan).permit(
      :title,
      :kind,
      :stripe_uid,
      :request_pool_size,
      :fee_in_cents,
      :has_cors,
      :has_ssl,
      :has_upc_lookup,
      :has_upc_value,
      :has_history
    )
  end
end

app/views/admin/plans/index.html.erb
<section>
  <div class="page-header">
    <h1>Plans</h1>
  </div>

  <table class="table table-hover">
    <thead>
      <th>Title</th>
      <th>Users</th>
    </thead>
    <tbody>
      <% @plans.each do |plan| %>
        <tr>
          <td><%= link_to plan.title, admin_plan_path(plan) %></td>
          <td><%= plan.users_count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/admin/plans/show.html.erb
<section>
  <div class="page-header">
    <h1>Plan</h1>
  </div>

  <%= form_for [:admin, @plan] do |f| %>
    <fieldset>
      <legend>Info</legend>
      <% if @plan.respond_to?(:users_count) %>
        <div class="form-group">
          <label>Active Users</label>
          <p class="form-control-static">
            <%= link_to @plan.users_count, admin_users_path(plan_id: @plan.id) %>
          </p>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :kind %>
        <p class="form-control-static">
          <%= f.select :kind, Plan.kinds.keys %>
        </p>
      </div>
      <div class="form-group">
        <%= f.label :stripe_uid, 'Stripe UID' %>
        <%= f.text_field :stripe_uid, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :request_pool_size %>
        <%= f.text_field :request_pool_size, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :fee_in_cents %>
        <%= f.text_field :fee_in_cents, class: 'form-control' %>
      </div>
    </fieldset>

    <fieldset>
      <legend>Attributes</legend>
      <div class="checkbox">
        <label>
          <%= f.check_box :has_cors %> Has CORS
        </label>
      </div>
      <div class="checkbox">
        <label>
          <%= f.check_box :has_ssl %> Has SSL
        </label>
      </div>
      <div class="checkbox">
        <label>
          <%= f.check_box :has_upc_lookup %> Has UPC Lookup
        </label>
      </div>
      <div class="checkbox">
        <label>
          <%= f.check_box :has_upc_value %> Has UPC Values
        </label>
      </div>
      <div class="checkbox">
        <label>
          <%= f.check_box :has_history %> Has History
        </label>
      </div>
    </fieldset>

    <div class="form-group">
      <button type="submit" class="btn btn-success">
        Save
      </button>

      <% if @plan.persisted? %>
        <%= link_to 'Clone', clone_admin_plan_path(@plan), class: 'btn', data: { method: :put } %>
      <% end %>
    </div>

    <% if @plan.persisted? && @plan.users_count == 0 %>
      <fieldset>
        <legend>DANGER ZONE</legend>
        <%= link_to 'Delete Plan', admin_plan_path(@plan), class: 'btn btn-danger', data: { method: :delete, confirm: 'Are you sure you want to destroy this plan?' } %>
      </fieldset>
    <% end %>
  <% end %>
</section>