config/routes.rb
many_id_re = /([a-z0-9\-]+\,[a-z0-9\-]+\,{0,1})+/

Rails.application.routes.draw do
  controller :letsencrypt do
    get '/.well-known/acme-challenge/gNCtCbL-vk4TWp3wZAUBz5MF5kxwHEQaFOwUmM1JLb4' => :show
  end

  namespace :api, path: '/', format: :json do
    namespace :v2, path: '(v2)', constraints: APIConstraint.new(2) do
      namespace :manager do
        controller :accounts do
          get    '/account'  => :show,   as: :account
          put    '/account'  => :update
          delete '/account'  => :destroy
          post   '/accounts' => :create, as: :accounts
        end

        controller :verifications do
          put '/verifications/:token' => :update
        end

        controller :passwords do
          post '/passwords'        => :create
          put  '/passwords/:token' => :update
        end

        controller :sessions do
          get    '/session'  => :show,    as: :session
          delete '/session'  => :destroy
          put    '/session'  => :update
          post   '/sessions' => :create,  as: :sessions
        end

        controller :keys do
          get    '/keys'     => :index,  as: :keys
          post   '/keys'     => :create
          get    '/keys/:id' => :show,   as: :key
          put    '/keys/:id' => :update
          delete '/keys/:id' => :destroy
        end
      end

      match '*path', to: 'api#preflight_cors', via: :options

      controller :datasets do
        get '/datasets'     => :index, as: :datasets
        get '/datasets/:id' => :index, constraints: { id: many_id_re }
        get '/datasets/:id' => :show,  as: :dataset
      end

      controller :inventories do
        get '/inventories'     => :index, as: :inventories
        get '/inventories/:id' => :index, constraints: { id: many_id_re }
        get '/inventories/:id' => :show, as: :inventory
        get '/products/:product_id/stores/:store_id' => redirect('/inventories/%{product_id}-%{store_id}')
        get '/stores/:store_id/products/:product_id' => redirect('/inventories/%{product_id}-%{store_id}')
      end

      controller :products do
        get '/products'     => :index, as: :products
        get '/products/:id' => :index, constraints: { id: many_id_re }
        get '/products/:id' => :show,  as: :product
      end

      controller :stores do
        get '/stores'     => :index, as: :stores
        get '/stores/:id' => :index, constraints: { id: many_id_re }
        get '/stores/:id' => :show,  as: :store
      end

      controller :producers do
        get '/producers'     => :index, as: :producers
        get '/producers/:id' => :index, constraints: { id: many_id_re }
        get '/producers/:id' => :show,  as: :producer
      end

      controller :categories do
        get '/categories'     => :index, as: :categories
        get '/categories/:id' => :index, constraints: { id: many_id_re }
        get '/categories/:id' => :show,  as: :category
      end
    end

    scope module: :v1, path: '(v1)', constraints: APIConstraint.new(1, true) do
      match '*path', to: 'api#preflight_cors', via: :options

      # Legacy V1
      get '/products/search'                          => 'products#index'
      get '/products/:product_id/inventory'           => 'inventories#index'
      get '/stores/search'                            => 'stores#index'
      get '/stores/near/geo(/with/:product_id)'       => 'stores#index',    is_geo_q: true
      get '/stores/near/:geo(/with/:product_id)'      => 'stores#index'
      get '/stores/near/:lat/:lon(/with/:product_id)' => 'stores#index', constraints: { lat: GeoScope::LATLON_RE, lon: GeoScope::LATLON_RE }
      get '/stores/:store_id/products/search'         => 'products#index'

      resources :datasets, only: [:index, :show]

      resources :products, only: [:index, :show] do
        resources :inventories, only: [:index], controller: 'inventories'
        resources :stores,      only: [:index]
      end

      resources :stores, only: [:index, :show] do
        resources :products, only: [:index] do
          get 'inventory' => 'inventories#show', as: :store_inventory
        end
      end

      resources :inventories, only: [:index]
    end
  end

  scope controller: :root, action: :ember, format: :html do
    get '/sign-up'      => redirect('/manager/sign-up')
    get '/log-in'       => redirect('/manager/log-in')
    get '/manage'       => redirect('/manager')
    get '/manage/*path' => redirect('/manager/%{path}')
    get '/manager'
    get '/manager/log-in'
    get '/manager/sign-up'
    get '/manager/verify/:token',   as: :verify_token
    get '/manager/password/recover'
    get '/manager/password/:token', as: :password
    get '/manager/account'
    get '/manager/keys'
    get '/manager/keys/new'
    get '/manager/keys/:key_id'
    get '/manager/credits'
    get '/manager/terms'
    get '/manager/privacy'
  end

  namespace :admin do
    root to: 'crawls#index'

    resources :crawls
    resources :crawl_events
    resources :users

    resources :plans do
      member do
        put :clone
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  SESSION_TTL = 3.weeks
  NAME_RE     = /\A[[:alpha:] '\-]+\Z/u
  MAX_RATE    = 1000
  TRUTHS      = [1, true, '1', 't', 'true', 'yes']

  has_many :keys,   dependent: :destroy
  has_many :emails, dependent: :destroy

  belongs_to :plan, optional: true

  before_create :generate_auth_secret, :generate_verification_secret
  before_save   :set_password_digest, if: :password_changed?

  before_validation :assign_default_plan

  after_create  :welcome_and_update_email
  after_update  :update_email,  if: :email_changed?
  after_save    :redis_cache

  validates :plan_id, presence: true

  validates :password,
    presence: true,
    length: { minimum: 8, maximum: 200 },
    if: :password_given?

  validates :new_password,
    presence: true,
    length: { minimum: 8, maximum: 200 },
    if: :new_password_given?

  validates :name,
    presence: true,
    format: {
      with: NAME_RE,
      message: I18n.t('user.invalid_name')
    }

  validate :validate_password_change, if: :new_password_given?
  validate :validate_email_presence,  if: :new_record?
  validate :validate_email,           if: :email_changed?
  validate :validate_terms_agreement, on: :create

  scope :verified, -> { where.not(email: nil) }

  scope :with_keys_count, -> {
    select('users.*, count(keys.id) AS keys_count').
    joins('LEFT OUTER JOIN keys ON keys.user_id = users.id').
    group('users.id')
  }

  attr_reader \
    :password,
    :new_password,
    :new_email

  def self.challenge(params)
    email    = params[:email].to_s.downcase
    password = params[:password]

    return if email.blank? || password.blank?

    if (found = verified.where('LOWER(email) = ?', email).first)
      return if (password_digest = found.password_digest).blank?
      password_digest == password ? found : nil
    else
      nil
    end
  end

  def self.lookup(raw_token)
    return unless token = Token.parse(raw_token)

    if token.is?(:session)
      lookup_session_token(token)
    elsif token.is?(:auth)
      lookup_auth_token(token)
    elsif token.is?(:verification)
      lookup_verification_token(token)
    end
  rescue ActiveRecord::StatementInvalid
    nil
  end

  def self.lookup_auth_token(token)
    return unless user = verified.where(id: token[:user_id]).first

    if SecureCompare.compare(user.auth_secret, token[:secret])
      user
    else
      nil
    end
  end

  def self.lookup_session_token(token)
    return unless json = $redis.get(redis_session_key(token))
    payload = JSON.parse(json)

    if SecureCompare.compare(token[:secret], payload['secret'])
      where(id: payload['user_id']).first
    else
      nil
    end
  end

  def self.lookup_verification_token(token)
    return unless user = where(id: token[:user_id]).first

    if SecureCompare.compare(user.verification_secret, token[:secret])
      user
    else
      nil
    end
  end

  def self.redis_session_key(token)
    "#{Rails.env}:sessions:#{token[:user_id]}"
  end

  def self.redis_user_key(user_id)
    "#{Rails.env}:users:#{user_id}"
  end

  def self.redis_total_requests_key(user_id)
    "#{redis_user_key(user_id)}:total_requests"
  end

  def self.redis_cycle_total_requests_key(user_id, cycle)
    "#{redis_user_key(user_id)}:cycles:#{cycle}:total_requests"
  end

  def self.redis_cycle_daily_request_totals_key(user_id, cycle)
    "#{redis_user_key(user_id)}:cycles:#{cycle}:daily_request_totals"
  end

  def self.redis_cycles_key(user_id)
    "#{redis_user_key(user_id)}:cycles"
  end

  def self.redis_load(user_id)
    if (json = $redis.get(redis_user_key(user_id)))
      MultiJson.load(json, symbolize_keys: true)
    else
      redis_cache(user_id)
    end
  end

  def self.redis_cache(user_id)
    User.find(user_id).redis_cache
  end

  def does_agree_to_terms=(val)
    @does_agree_to_terms = TRUTHS.include?(val)
  end

  def max_rate
    MAX_RATE
  end

  def password_changed?
    return true if new_record?
    @password_changed ? true : false
  end

  def password_given?
    new_record? || (@password_given ? true : false)
  end

  def password=(val)
    @password_given = true
    @password_changed = true
    @password = val
  end

  def new_password_given?
    @new_password_given ? true : false
  end

  def new_password=(val)
    @new_password_given = true
    @new_password = val
    self.password = val
    @password_given = false
  end

  def current_password=(val)
    @current_password = val
  end

  def password_digest
    BCrypt::Password.new(read_attribute(:password_digest))
  end

  def first_name
    name.present? ? name.split(' ')[0] : nil
  end

  def email_contact
    "#{name} <#{email}>"
  end

  def email_changed?
    return true if new_record?
    @email_changed ? true : false
  end

  def email=(val)
    @email_changed = true
    @new_email = emails.build(address: val)
  end

  def generate_auth_secret
    self.auth_secret = Token.generate_secret
  end

  def generate_verification_secret
    self.verification_secret = Token.generate_secret
  end

  def verification_token
    Token.new(:verification, user_id: id, secret: verification_secret)
  end

  def auth_token
    Token.new(:auth, user_id: id, secret: auth_secret)
  end

  def generate_session_token
    token = Token.generate(:session, user_id: id)
    json = %|{"user_id":"#{id}","secret":"#{token[:secret]}"}|
    $redis.setex(redis_session_key(token), SESSION_TTL, json)
    token
  end

  def session_token_ttl(token)
    $redis.ttl(redis_session_key(token))
  end

  def refresh_session_token(token)
    $redis.expire(redis_session_key(token), User::SESSION_TTL)
  end

  def destroy_session_token(token)
    $redis.del(redis_session_key(token))
  end

  def assign_email_address!(email)
    e = Email.verified.where(address: email).first!
    write_attribute :email, e.address
    save!
  end

  def cycle_requests
    now    = Time.now
    first  = now.beginning_of_month.to_date
    last   = now.end_of_month.to_date
    rkey   = User.redis_cycle_daily_request_totals_key(id, first.strftime('%Y-%m'))
    scores = Hash[$redis.zrange(rkey, 0, -1, withscores: true)]
    ret    = []

    first.upto(last) do |date|
      isodate = date.to_s
      ret << [isodate, (scores[isodate] || 0).to_i]
    end

    ret
  end

  def redis_cache
    key  = self.class.redis_user_key(id)
    $redis.set(key, MultiJson.dump(
      has_cors:          plan.has_cors,
      has_ssl:           plan.has_ssl,
      has_upc_lookup:    plan.has_upc_lookup,
      has_upc_value:     plan.has_upc_value,
      has_history:       plan.has_history,
      request_pool_size: plan.request_pool_size,
      is_disabled:       is_disabled
    ))
    self.class.redis_load(id)
  end

  def cycle_ends_on
    Time.now.end_of_month.to_date
  end

  private

  def assign_default_plan
    return true if plan_id
    self.plan_id = Plan.free.first.id
    true
  end

  def redis_session_key(token)
    self.class.redis_session_key(token)
  end

  def validate_terms_agreement
    return true if persisted?
    return true if @does_agree_to_terms

    errors.add :does_agree_to_terms, 'sign up requires that you agree to the TOS'
  end

  def validate_password_change
    return true unless new_password_given?
    return true if password_digest == @current_password.to_s

    errors.add :current_password, 'is not correct'
  end

  def validate_email_presence
    return true unless new_record?
    return true if @new_email

    errors.add :email, 'must be provided'
  end

  def validate_email
    return true unless @new_email
    return true if @new_email.valid?

    @new_email.errors[:address].each do |error|
      errors.add(:email, error)
    end

    true
  end

  def welcome_and_update_email
    return unless @new_email
    @new_email.save_with_welcome_verification_message
  end

  def update_email
    return unless @new_email
    @new_email.save_with_verification_message
  end

  def set_password_digest
    return true unless password_changed?
    self.password_digest = BCrypt::Password.create(@password)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    if params[:plan_id]
      @plan = Plan.with_users_count.find(params[:plan_id])
      @users = @plan.users.with_keys_count.order(created_at: :desc)
    else
      @users = User.with_keys_count.order(created_at: :desc)
    end
  end

  def show
    @user = User.includes(:emails, :keys, :plan).find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_url(@user)
    else
      render :show
    end
  end

  def destroy
    @user = User.find(params[:id])

    if @user.is_disabled? || @user.email.blank?
      @user.destroy
      redirect_to admin_users_url
    else
      redirect_to admin_user_url(@user)
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :plan_id,
      :is_disabled
    )
  end
end

app/views/admin/users/index.html.erb
<section>
  <div class="page-header">
    <% if @plan %>
      <h1>Users <small>of the <%= link_to @plan.title, admin_plan_path(@plan) %> plan</small></h1>
    <% else %>
      <h1>Users</h1>
    <% end %>
  </div>

  <table class="table table-hover">
    <thead>
      <th>Name</th>
      <th>Email</th>
      <th>Keys</th>
      <th>Activity</th>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr >
          <td><%= link_to user.name, admin_user_path(user) %></td>
          <td><%= user.email %></td>
          <td><%= user.keys_count %></td>
          <td><%= user.cycle_requests.reduce(0) { |m,r| m + r[1] } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/admin/users/show.html.erb
<section>
  <div class="page-header">
    <h1>User<% if @user.is_disabled %> <span class="label label-danger">Disabled</span><% end %></h1>
  </div>

  <%= form_for [:admin, @user] do |f| %>
    <fieldset>
      <legend>Info</legend>
      <div class="form-group">
        <label>ID</label>
        <p class="form-control-static">
          <%= @user.id %>
        </p>
      </div>
      <div class="form-group">
        <label>Joined</label>
        <p class="form-control-static">
          <%= @user.created_at.strftime("%B #{@user.created_at.day.ordinalize}, %Y") %>
        </p>
      </div>
      <% if @user.last_seen_at %>
        <div class="form-group">
          <label>Last Seen</label>
          <p class="form-control-static">
            <%= @user.last_seen_at.strftime("%B #{@user.last_seen_at.day.ordinalize}, %Y") %>
            <% if last_seen_ip = @user.last_seen_ip %>
              (<%= last_seen_ip %>)
            <% end %>
          </p>
        </div>
      <% end %>
      <div class="form-group">
        <label>Name</label>
        <p class="form-control-static">
          <%= @user.name %>
        </p>
      </div>
      <div class="form-group">
        <%= f.label :plan %>
        <p class="form-control-static">
          <%= f.select :plan_id, Plan.select_options %>
        </p>
      </div>
      <div class="checkbox">
        <label>
          <%= f.check_box :is_disabled %> Disabled
        </label>
      </div>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Email Address</th>
            <th>Approved</th>
          </tr>
        </thead>
        <tbody>
          <% @user.emails.each do |email| %>
            <tr>
              <td><%= email.address %></td>
              <td><b><%= email.is_verified ? 'Yes' : 'No' %></b></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </fieldset>

    <fieldset>
      <legend>Keys</legend>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Label</th>
            <th>Kind</th>
            <th>Total Requests</th>
            <th>Info</th>
          </tr>
        </thead>
        <tbody>
          <% @user.keys.each do |key| %>
            <tr>
              <td><%= key.label %></td>
              <td>
                <%= key.kind.titlecase %>
                <% if key.domain.present? %>
                  <span class="label"><%= key.domain %></span>
                <% end %>
              </td>
              <td><%= key.total_requests %></td>
              <td><small><%= key.info %></small></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </fieldset>

    <div class="form-group">
      <button type="submit" class="btn btn-success">
        Save
      </button>
    </div>

    <% if @user.is_disabled? || @user.email.blank? %>
      <fieldset>
        <legend>DANGER ZONE</legend>
        <%= link_to 'Delete User', admin_user_path(@user), class: 'btn btn-danger', data: { method: :delete, confirm: 'Are you sure you want to delete this user?' } %>
      </fieldset>
    <% end %>
  <% end %>
</section>